name: Run pytest

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup venv & pip install
        run: python3 -m venv .venv && .venv/bin/pip install -r requirements.txt

      - name: run pytest
        run: pytest
